### ISSUE TITLE
Add epoch relative to rest-frame maximum to spectra tooltips

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/astrocats#1]

**Comment by guillochon** [comment]
@jparrent This has now been done, let me know if what we have is satisfactory.

**Comment by jparrent** [comment]
@guillochon SUPER. I'm guessing everything is accurate when it comes to your rest-frame correction (cf. Blondin et al. http://arxiv.org/abs/0804.3595 if you want to compare to what they did). But I'll keep a an eye out.

Initially I went to 11fe to check on this since it's nearby (M101; z = 0.0008). It's first spectrum has a reported epoch of -15.2 days (Pereira et al. 2013; http://adsabs.harvard.edu/abs/2013A%26A...554A..27P), whereas our rest-frame epoch says -10.69. My first thought was, does this relativistic correction really shave off ~3-4 days, even for a nearby event such as 11fe? Seems a bit high. From a relatively quick scanning Blondin et al., I'm still surprised that we shave 3-4 days for 11fe. For low-z SN Ia, I would expect shaving something closer to 0.1-1.0 day.

My next thought was, I expect a few to several of the dates of maximum to be off -- turns out this is correct for 11fe in the catalog. Its max B-band date can be updated from 2011 Sep 6 to 2011 Sep 10 (MJD = 55814.51)--i.e. ^3-4 day difference. I'll create a separate issue for this.

**Comment by jparrent** [comment]
For whatever reason I cannot close this issue, but it can be closed now.
