### ISSUE TITLE
[2011fe] date of maximum

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/astrocats#4]
@guillochon Its max B-band date can be updated from 2011 Sep 6 to 2011 Sep 10 (MJD = 55814.51).

Pereira et al. 2013
http://adsabs.harvard.edu/abs/2013A%26A...554A..27P

**Comment by guillochon** [comment]
So it looks like reviewing the code that we were missing the Lennarz reference max dates due to a typo in that section of the code. I'm taking this opportunity to also simplify our date format a bit, previously, we had four variables for each date: year, month, day, and date. The reason for this was that some events we might have only known the year or maybe the year and month; to specify this now we'll just omit that information from the date. I'll update this issue again once the changes go live.

Some questions about convention: Should we always use the V-band to specify max date if for a given event it is not specified? If we want to use V-band, what should we do when V-band is not available? Or should we use the brightest photometric point across all bands?

I'm leaning towards doing some sort of basic fitting to determine the peak magnitudes if they are not provided in a reference, this doesn't have to be bulletproof but it will do better than using the brightest point, which is ambiguous in many cases.

**Comment by jparrent** [comment]
re: convention questions. 
Generally folks have quoted maximum light wrt B-band, V-band, or peak bolometric luminosity, when available. So long as it is specified, users of the Open Supernova Catalog will understand. Usually the difference between B-band and V-band maximum is a couple of days, and most studies that look to take a slice in epochs apply a window of +/- 3-5 days to skirt such issues. Once I am done scouting redshift corrections, next on the list will be rummaging through dates of maximum. 

As for the fitting, agreed, it would provide at least a basic reference point (+/- 1-3 days).

**Comment by jparrent** [comment]
@guillochon Was going to close this one, but date of maximum for 11fe needs to be changed from Sept 6 2011 to Sept 10. I can do this one by hand unless you would like to scriptify.

**Comment by guillochon** [comment]
Had literally just updated SN2011fe with the script, check it now.

We're now using B band (and B-like bands) preferentially for the max date, followed by V band (or V-like bands), then R band (or R-like bands). If none of those bands are available then it just uses the maximum based upon all bands. The band used to determine the max is now denoted after the magnitudes are listed.

**Comment by jparrent** [comment]
Hah. All done!
