### ISSUE TITLE
[SN 2003aa] Ic, not Ia

### ISSUE THREAD

**Issue by jparrent** [astrocatalogs/astrocats#41]
@guillochon So it turns out this one was being flagged as a Ia, when it's a Ic.

SUPERNOVA 2003aa IN NGC 3367
     Further to IAUC 8063, T. Matheson, P. Challis, and R. Kirshner
report that a spectrum (range 370-750 nm) of SN 2003aa (cf. IAUC
8063), obtained by P. Berlind with the 1.5-m reflector on Feb. 2.31
UT, shows it to be a type-Ic supernova.  The spectrum is similar to
that of SN 1994I, four days before maximum (Filippenko et al. 1995,
Ap.J. 450, L11).

I flagged the claimedtype of Ia as erroneous and wanted to update the value to Ic. I thought I could do this via the pencil icon but then got an error. What did I miss?
![screen shot 2016-05-29 at 2 02 17 pm](https://cloud.githubusercontent.com/assets/7276612/15635206/547634de-25a6-11e6-93cb-c28a774a0988.png)

**Comment by guillochon** [comment]
So the pencil links only update after an import has been performed, so if
you try to do two different actions in a row on the same event before the
next import, you'll get an error because a file was created already by the
first action.

Easiest thing to do is just copy the JSON into the already existing file in
sne-internal. All changes will be caught in the next import.

On Sun, May 29, 2016 at 2:05 PM, J. Parrent notifications@github.com
wrote:

> @guillochon https://github.com/guillochon So it turns out this one was
> being flagged as a Ia, when it's a Ic.
> 
> SUPERNOVA 2003aa IN NGC 3367
> Further to IAUC 8063, T. Matheson, P. Challis, and R. Kirshner
> report that a spectrum (range 370-750 nm) of SN 2003aa (cf. IAUC
> 8063), obtained by P. Berlind with the 1.5-m reflector on Feb. 2.31
> UT, shows it to be a type-Ic supernova. The spectrum is similar to
> that of SN 1994I, four days before maximum (Filippenko et al. 1995,
> Ap.J. 450, L11).
> 
> I flagged the claimedtype of Ia as erroneous and wanted to update the
> value to Ic. I thought I could do this via the pencil icon but then got an
> error. What did I miss?
> [image: screen shot 2016-05-29 at 2 02 17 pm]
> https://cloud.githubusercontent.com/assets/7276612/15635206/547634de-25a6-11e6-93cb-c28a774a0988.png
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/astrocatalogs/sne/issues/41, or mute the thread
> https://github.com/notifications/unsubscribe/AExDqtJXg0W7p24-qRwIOwfYjmQqDJTjks5qGdWEgaJpZM4IpV9G
> .

## 

James Guillochon
Einstein Fellow at the Harvard-Smithsonian CfA
jguillochon@cfa.harvard.edu

**Comment by jparrent** [comment]
Got it. Thanks!
