### ISSUE TITLE
SN1987A photometry mismatch between sources

### ISSUE THREAD

**Issue by guillochon** [astrocatalogs/astrocats#8]
@jparrent I'd like to figure out exactly why the SUSPECT and the data pulled from Sternberg seem to disagree in regards to the photometry, which is most prominently visible in the I-band (almost a half mag difference between the two sources), but is also apparent in the other bands as well. As far as I can tell, both Sternberg and SUSPECT pulled this data from the same batch of papers from Whitelock and Catchpole. Any idea why the two are different?

**Comment by jparrent** [comment]
@guillochon OK so I _think_ I've figured out what's going on, at least for the I-band. There are 4 datasets being pulled for the I-band. Three of them are Catchpole et al. (1987, 1988, 1989), the last two of which are coming from Sternberg, whereas the first Catchpole points (1987) are coming from SuSpect. And all three of these datasets are the topmost I-band light curve in the plot. It's the fourth set of points, the ones that are noticeably off, that are coming from SuSpect, and those points are actually from [Suntzeff et al. (1988)](http://adsabs.harvard.edu/abs/1988AJ.....96.1864S), but it's being marked as Catchpole et al. (1987) in the plot/source number (1,2). I have also confirmed that the values for the fourth set are the same as they are in Suntzeff et al.

Turns out Suntzeff et al. point out these 0.3 magnitude differences, although I'm not sure I follow the reason behind the systematic differences: ``There are large systematic differences of up to 0.3 mag between the CTIO photometry and other published photometry due to the presence of strong emission lines during this exponential-decline phase.''

At any rate, the reference for the "off points" should be updated to Suntzeff et al., linked above. I'm guessing the UBVRI from Suntzeff [(SuSpect)](https://www.nhn.ou.edu/cgi-bin/cgiwrap/~suspect/search.cgi?phot=yes&OBJECT=1987A) just got lumped together with the Catchpole reference at some point. I think I could manage to go and edit this by hand, but if you want to see if it's a script problem, have at it.

**Comment by guillochon** [comment]
@jparrent Thanks for looking into this, I see now that there's a bug in the code pulling from SUSPECT, it is using the first source found for a given even as the source for all data for that event name, hence the Catchpole reference was being used instead of Suntzeff. I think I've fixed this, will go live with the next update.

It's also interesting that there's a real difference between the two sets of photometry. At least we now know the stated reason.

**Comment by guillochon** [comment]
This issue is now fixed, the sources are now properly shown as being different for 1987A (and a number of other events for which SUSPECT was being scraped for).
